<a href="https://colab.research.google.com/github/HRK98it/OneHotEncoder_cat_var_into_num/blob/main/label_%26_ordinal_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [6]:
from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/MyDrive/Colab Notebooks/train.csv"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
try:
  df=pd.read_csv(file_path)
except FileNotFoundError:
  print(f"File not found at path: {file_path}")

In [11]:
pd.set_option('display.max_columns', None)
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

**the lable encoder work with both ordinal and nominal data but it convert into num by assigning the numeric value depend on the alphabetic order (e.g a=0 ,b=1 ,c=3)**

In [12]:
df2=df[['KitchenQual','BldgType']]

In [13]:
le=LabelEncoder()

In [15]:
arr = le.fit_transform(df['BldgType'])

In [17]:
df2['BldgType_N']=arr
df2

/tmp/ipython-input-17-1118036202.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['BldgType_N']=arr

     KitchenQual BldgType  BldgType_N
0             Gd     1Fam           0
1             TA     1Fam           0
2             Gd     1Fam           0
3             Gd     1Fam           0
4             Gd     1Fam           0
...          ...      ...         ...
1455          TA     1Fam           0
1456          TA     1Fam           0
1457          Gd     1Fam           0
1458          Gd     1Fam           0
1459          TA     1Fam           0

[1460 rows x 3 columns]

In [18]:
df2['BldgType_N'].value_counts()

BldgType_N
0    1220
4     114
2      52
3      43
1      31
Name: count, dtype: int64

In [20]:
ser=df2[df2['BldgType_N']==4]
ser

     KitchenQual BldgType  BldgType_N
23            TA   TwnhsE           4
34            Ex   TwnhsE           4
45            Ex   TwnhsE           4
62            Gd   TwnhsE           4
81            TA   TwnhsE           4
...          ...      ...         ...
1421          TA   TwnhsE           4
1422          Gd   TwnhsE           4
1431          TA   TwnhsE           4
1441          Gd   TwnhsE           4
1452          TA   TwnhsE           4

[114 rows x 3 columns]

# **ORDERED ENCODING**
In this the encoding is applied depend on the ordered

In [ ]:
'''
# EXAMPLE

In KitchenQual there are 4 classes

Ex == Excellent
Gd == Good
Ta == Typical/Average
Fa == Fair
'''
'''
We can gieve default priority number to each class like Ex=1, Gd=2 etc

In [21]:
df['KitchenQual'].value_counts()

KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

In [22]:
# we use dictionary to give priority

order_label = {'Ex':4,'Gd':3,'TA':2,'Fa':1}

In [23]:
df2['Kitchen_ord_enc']=df['KitchenQual'].map(order_label)
df2

/tmp/ipython-input-23-3705658109.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Kitchen_ord_enc']=df['KitchenQual'].map(order_label)

     KitchenQual BldgType  BldgType_N  Kitchen_ord_enc
0             Gd     1Fam           0                3
1             TA     1Fam           0                2
2             Gd     1Fam           0                3
3             Gd     1Fam           0                3
4             Gd     1Fam           0                3
...          ...      ...         ...              ...
1455          TA     1Fam           0                2
1456          TA     1Fam           0                2
1457          Gd     1Fam           0                3
1458          Gd     1Fam           0                3
1459          TA     1Fam           0                2

[1460 rows x 4 columns]